In [33]:
import pandas as pd
import os

In [44]:
files = [f'../data/raw/EURUSD_15min_{year}_Q{quartal}.csv'
         for year in range(2015, 2027)
         for quartal in range(1, 5)]
# оставим только существующие файлы
files = [f for f in files if os.path.exists(f)]

# Чтение и объединение
dfs = [pd.read_csv(f) for f in files]
df = pd.concat(dfs, ignore_index=True)

# Обработка времени
df['timestamp'] = pd.to_datetime(df['timestamp'],utc=False).dt.tz_localize(None)
df = df.drop_duplicates(subset=['timestamp']).sort_values('timestamp').reset_index(drop=True)

In [47]:
df.head()

            timestamp     open     high      low    close   volume
0 2014-12-31 18:00:00  1.20997  1.21070  1.20997  1.21048  1118.83
1 2014-12-31 18:15:00  1.21047  1.21079  1.21042  1.21067   523.99
2 2014-12-31 18:30:00  1.21068  1.21069  1.21000  1.21019   690.66
3 2014-12-31 18:45:00  1.21018  1.21018  1.20984  1.21010   725.78
4 2014-12-31 19:00:00  1.21010  1.21037  1.20982  1.20997   750.45

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 277105 entries, 0 to 277104
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   timestamp  277105 non-null  datetime64[us]
 1   open       277105 non-null  float64
 2   high       277105 non-null  float64
 3   low        277105 non-null  float64
 4   close      277105 non-null  float64
 5   volume     277105 non-null  float64
dtypes: datetime64[us](1), float64(5)
memory usage: 12.7 MB

In [49]:
#поставим timestamp индексом
df.set_index('timestamp', inplace=True)
df.head()

                        open     high      low    close   volume
timestamp
2014-12-31 18:00:00  1.20997  1.21070  1.20997  1.21048  1118.83
2014-12-31 18:15:00  1.21047  1.21079  1.21042  1.21067   523.99
2014-12-31 18:30:00  1.21068  1.21069  1.21000  1.21019   690.66
2014-12-31 18:45:00  1.21018  1.21018  1.20984  1.21010   725.78
2014-12-31 19:00:00  1.21010  1.21037  1.20982  1.20997   750.45

In [50]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 277105 entries, 2014-12-31 18:00:00 to 2026-03-26 16:30:00
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   open    277105 non-null  float64
 1   high    277105 non-null  float64
 2   low     277105 non-null  float64
 3   close   277105 non-null  float64
 4   volume  277105 non-null  float64
dtypes: float64(5)
memory usage: 12.7 MB